### ISSUE TITLE
Account for uninstall deployment collection naming convention and output collections found with no deployments

### ISSUE THREAD

**Issue by mmseng** [engrit-illinois/Get-CMOrgModelDeploymentRules#2]
Currently I believe this module will never identify our uninstall collections, since we generally name them like `UIUC-ENGR-Uninstall*` or `UIUC-ENGR-IS Uninstall*`. These aren't very common, but it would be nice to include these in the report.

Also, the module currently skips over collections which it finds to have no deployments. I think it would be useful to include these in the report, with just blank data in the relevant columns, as it would help us identify missing deployments or deployment collections which can be retired/deleted.

Just noting these potential improvements for later.

**Comment by han44-illinois** [comment]
I think we have been inconsistent with the naming of our uninstall collections. I'd have to check, but iirc last time I used the `New-CMOrgModelDeploymentCollection` module with the `-Uninstall` flag, it did not name the collections as you describe. If that behavior has changed and the naming is standardized within that module, I'll also modify this one to match.

**Comment by mmseng** [comment]
`New-CMOrgModelDeploymentCollection` should name them like this: https://github.com/engrit-illinois/New-CMOrgModelDeploymentCollection/blob/e0951d34833583245c1c28f76f6bff6f483356c5/New-CMOrgModelDeploymentCollection.psm1#L146-L148

**Comment by mmseng** [comment]
Resolved in b64ebb1e6a9b35b562b8e4703136552ce6474193
